services:
  db:
    image: postgres:18-alpine
    container_name: restaurant_management_db
    restart: always
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DATABASE}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "${SPRING_DATASOURCE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  app:
    build: .
    container_name: restaurant_management_app
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "127.0.0.1:5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${SPRING_DATASOURCE_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_PORT: ${SPRING_DATASOURCE_PORT}
      SPRING_DATASOURCE_DATABASE: ${SPRING_DATASOURCE_DATABASE}
      SPRING_PROFILES_ACTIVE: dev
      APP_PORT: ${APP_PORT}
    volumes:
      - .:/app:delegated # Espelha código fonte
      - app_target:/app/target # Isola classes geradas/compiladas do container; evita conflito com target do host
      - maven_cache:/root/.m2 # Volume nomeado para persistir dependências Maven
    # Comando que inicia o Spring com DevTools e suporte a Debug
    command: ./mvnw spring-boot:run -Dmaven.test.skip=true -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

volumes:
  pgdata:
  app_target:
  maven_cache:
